"""Discreet labels in the Canvas top margin, after artwork placement."""

from io import BytesIO

import fitz
from pypdf import PdfReader

LABELS = {
	"TROQUEL": "TROQUEL & DIMENSIONES",
	"RELIEVE": "RELIEVE",
	"ESTAMPADO": "ESTAMPADO",
	"BARNIZ BRILLO": "BARNIZ BRILLO",
	"BARNIZ MATTE": "BARNIZ MATTE",
}


def add_separation_label(page, source_page, top_margin, right_margin):
	"""Label only pages generated by the separator; preserve artwork at full size.

	All installed Canvas templates reserve a top margin. A custom Canvas with
	no such margin is left intact rather than placing a label over its artwork.
	"""
	label = LABELS.get(getattr(source_page, "printcard_separation_label", None))
	if not label or top_margin <= 0:
		return
	width, height = float(page.mediabox.width), float(page.mediabox.height)
	font = fitz.Font("hebo")
	# Ten physical points stay discreet and legible even on the largest sheets.
	font_size = min(10, top_margin * 0.75 / (font.ascender - font.descender))
	text_width = font.text_length(label, fontsize=font_size)
	if text_width > width - max(0, right_margin):
		return
	x = width - max(0, right_margin) - text_width
	text_height = (font.ascender - font.descender) * font_size
	y = (top_margin - text_height) / 2 + font.ascender * font_size
	with fitz.open() as overlay:
		target = overlay.new_page(width=width, height=height)
		target.insert_text(
			(x, y), label, fontname="hebo", fontsize=font_size, color=(20 / 255, 28 / 255, 55 / 255)
		)
		page.merge_page(PdfReader(BytesIO(overlay.tobytes())).pages[0])
