"""Discreet labels in the Canvas top margin, after artwork placement."""

from io import BytesIO

import fitz
from pypdf import PdfReader

LABELS = {
	"ARTE + TROQUEL + PRESERVADO": "ARTE & TROQUEL",
	"TROQUEL": "TROQUEL & DIMENSIONES",
	"RELIEVE": "RELIEVE",
	"ESTAMPADO": "ESTAMPADO",
	"BARNIZ BRILLO": "BARNIZ BRILLO",
	"BARNIZ MATTE": "BARNIZ MATTE",
}


def add_separation_label(page, source_page, top_margin, right_margin):
	"""Label only pages generated by the separator; preserve artwork at full size.

	All installed Canvas templates reserve a top margin. A custom Canvas with
	no such margin is left intact rather than placing a label over its artwork.
	"""
	label = LABELS.get(getattr(source_page, "printcard_separation_label", None))
	if not label or top_margin <= 0:
		return
	width, height = float(page.mediabox.width), float(page.mediabox.height)
	font = fitz.Font("hebo")
	# A compact, softly rounded badge stays entirely inside the existing margin.
	badge_height = min(18, top_margin * 0.86)
	font_size = min(9.5, badge_height * 0.82 / (font.ascender - font.descender))
	padding = font_size
	leading = font_size * 2
	text_width = font.text_length(label, fontsize=font_size)
	badge_width = leading + text_width + padding
	if badge_width > width - max(0, right_margin):
		return
	right = width - max(0, right_margin)
	left = right - badge_width
	top = (top_margin - badge_height) / 2
	x = left + leading
	text_height = (font.ascender - font.descender) * font_size
	y = (top_margin - text_height) / 2 + font.ascender * font_size
	navy = (25 / 255, 56 / 255, 99 / 255)
	white = (1, 1, 1)
	with fitz.open() as overlay:
		target = overlay.new_page(width=width, height=height)
		target.draw_rect(
			fitz.Rect(left, top, right, top + badge_height),
			radius=0.25,
			color=navy,
			fill=navy,
			width=min(0.4, top_margin * 0.02),
		)
		target.draw_circle((left + padding, top_margin / 2), font_size * 0.15, color=None, fill=white)
		target.insert_text((x, y), label, fontname="hebo", fontsize=font_size, color=white)
		page.merge_page(PdfReader(BytesIO(overlay.tobytes())).pages[0])
